version: '3'

services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: qr-code-server
    ports:
      - "8000:8000"
      
  client:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile
    container_name: qr-code-client
    ports:
      - "3000:3000"
    depends_on:
      - server
